name: GitHub Comment

on:
  pull_request:
  pull_request_labeled:

jobs:
  github_comment:
    name: GitHub Comment
    type: github-comment
    params:
      message: "Testing GitHub comment"
      build_ids: [typo]
