name: Update

jobs:
  update_android:
    type: update
    params:
      channel: development
      platform: android
      message: testing this
      rollout_percentage: 10
  finalize_rollout:
    type: end-update-rollout
    needs: [update_android]
    params:
      action: promote
      group_id: ${{ needs.update_android.outputs.first_update_group_id }}
